Traceback (most recent call last):
  File "C:\Users\jkgv1\.conda\envs\Ubidots\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\jkgv1\.conda\envs\Ubidots\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\jkgv1\.conda\envs\Ubidots\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\jkgv1\.conda\envs\Ubidots\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\jkgv1\.conda\envs\Ubidots\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\jkgv1\.conda\envs\Ubidots\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\jkgv1\.conda\envs\Ubidots\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jkgv1\.conda\envs\Ubidots\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
PICKLED_DATA_FILENAME = 'data_monthly.pkl'
project_path = 'D:\OneDrive - CELSIA S.A E.S.P\Proyectos\Eficiencia_Energetica\Bancolombia\Experimental'

%load_ext autoreload
%autoreload 2
import warnings
# warnings.filterwarnings("ignore")


import pandas as pd
import numpy as np
from datetime import datetime
import requests
import json

from matplotlib import pyplot as plt
from matplotlib.ticker import PercentFormatter
import seaborn as sns

import plotly.io as pio
import plotly.graph_objects as go
import plotly.express as px
import plotly.offline as py

pio.renderers.default = "notebook"

from dotenv import load_dotenv
from dotenv import dotenv_values

from sys import exit
import os

import sys
from pathlib import Path

project_path = Path(project_path)
sys.path.append(str(project_path))

import config as cfg
from library_ubidots import Ubidots
import library_report as Report



_TOKEN = os.getenv("_token")
PICKLED_DATA_FILEPATH = project_path / 'data' / PICKLED_DATA_FILENAME
df = pd.read_pickle(PICKLED_DATA_FILEPATH)
df = df.query("device_name != 'BC 453 - Pitalito'")
df = df.query("device_name != 'BC 749 - Santa Monica'")
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [1;32mIn [1][0m, in [0;36m<cell line: 20>[1;34m()[0m
[0;32m     17[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mticker[39;00m [38;5;28;01mimport[39;00m PercentFormatter
[0;32m     18[0m [38;5;28;01mimport[39;00m [38;5;21;01mseaborn[39;00m [38;5;28;01mas[39;00m [38;5;21;01msns[39;00m
[1;32m---> 20[0m [38;5;28;01mimport[39;00m [38;5;21;01mplotly[39;00m[38;5;21;01m.[39;00m[38;5;21;01mio[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpio[39;00m
[0;32m     21[0m [38;5;28;01mimport[39;00m [38;5;21;01mplotly[39;00m[38;5;21;01m.[39;00m[38;5;21;01mgraph_objects[39;00m [38;5;28;01mas[39;00m [38;5;21;01mgo[39;00m
[0;32m     22[0m [38;5;28;01mimport[39;00m [38;5;21;01mplotly[39;00m[38;5;21;01m.[39;00m[38;5;21;01mexpress[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpx[39;00m

[1;31mModuleNotFoundError[0m: No module named 'plotly'
ModuleNotFoundError: No module named 'plotly'

